In [9]:
df = pd.read_csv(
    "online_retail.csv",
    encoding='ISO-8859-1',
    sep=';',
    engine='python'
)

In [10]:
df.shape
df.info()
df.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 173027 entries, 0 to 173026
Data columns (total 8 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   ï»¿InvoiceNo  173027 non-null  object
 1   StockCode     173027 non-null  object
 2   Description   172311 non-null  object
 3   Quantity      173026 non-null  float64
 4   InvoiceDate   173026 non-null  object
 5   UnitPrice     173026 non-null  float64
 6   CustomerID    121055 non-null  float64
 7   Country       173026 non-null  object
dtypes: float64(3), object(5)
memory usage: 10.6+ MB

,ï»¿InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6.0,01/12/2010 08:26,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6.0,01/12/2010 08:26,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8.0,01/12/2010 08:26,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6.0,01/12/2010 08:26,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6.0,01/12/2010 08:26,3.39,17850.0,United Kingdom

In [11]:
df = df.dropna(subset=['CustomerID'])

In [12]:
df['Return'] = df['Quantity'] < 0

In [13]:
df['Revenue'] = df['Quantity'] * df['UnitPrice']

In [14]:
df['InvoiceDate'] = pd.to_datetime(
    df['InvoiceDate'],
    dayfirst=True
)

In [15]:
df.rename(columns={'ï»¿InvoiceNo': 'InvoiceNo'}, inplace=True)

In [16]:
print(df.columns)

Index(['InvoiceNo', 'StockCode', 'Description', 'Quantity', 'InvoiceDate',
       'UnitPrice', 'CustomerID', 'Country', 'Return', 'Revenue'],
      dtype='object')

In [17]:
df.isnull().sum()

InvoiceNo      0
StockCode      0
Description    0
Quantity       0
InvoiceDate    0
UnitPrice      0
CustomerID     0
Country        0
Return         0
Revenue        0
dtype: int64

In [18]:
df.duplicated().sum()

np.int64(1488)

In [19]:
df = df.drop_duplicates()

In [20]:
df[df['Quantity'] < 0].head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,Return,Revenue
141,C536379,D,Discount,-1.0,2010-12-01 09:41:00,27.50,14527.0,United Kingdom,True,-27.50
154,C536383,35004C,SET OF 3 COLOURED FLYING DUCKS,-1.0,2010-12-01 09:49:00,4.65,15311.0,United Kingdom,True,-4.65
235,C536391,22556,PLASTERS IN TIN CIRCUS PARADE,-12.0,2010-12-01 10:24:00,1.65,17548.0,United Kingdom,True,-19.80
236,C536391,21984,PACK OF 12 PINK PAISLEY TISSUES,-24.0,2010-12-01 10:24:00,0.29,17548.0,United Kingdom,True,-6.96
237,C536391,21983,PACK OF 12 BLUE PAISLEY TISSUES,-24.0,2010-12-01 10:24:00,0.29,17548.0,United Kingdom,True,-6.96

In [21]:
df = df[(df['Quantity'] != 0) & (df['UnitPrice'] > 0)]

In [22]:
df['CustomerID'] = df['CustomerID'].astype(int)
df['InvoiceDate'] = pd.to_datetime(df['InvoiceDate'])

In [23]:
df['Cost'] = df['UnitPrice'] * 0.6
df['Profit'] = (df['UnitPrice'] - df['Cost']) * df['Quantity']

In [24]:
df.describe()

,Quantity,InvoiceDate,UnitPrice,CustomerID,Revenue,Cost,Profit
count,119556.000000,119556,119556.000000,119556.000000,119556.000000,119556.000000,119556.000000
mean,12.179840,2011-02-13 23:27:24.838903808,3.456066,15282.970876,20.766188,2.073640,8.306475
min,-74215.000000,2010-12-01 08:26:00,0.001000,12346.000000,-77183.600000,0.000600,-30873.440000
25%,2.000000,2011-01-07 12:28:00,1.250000,13842.000000,4.950000,0.750000,1.980000
50%,5.000000,2011-02-17 14:49:00,1.950000,15179.000000,11.900000,1.170000,4.760000
75%,12.000000,2011-03-25 12:04:00,3.750000,16833.000000,19.500000,2.250000,7.800000
max,74215.000000,2011-05-03 12:02:00,2382.920000,18283.000000,77183.600000,1429.752000,30873.440000
std,308.685877,NaN,21.257644,1729.442649,326.740454,12.754587,130.696182

In [25]:
returns = df[df['Quantity'] < 0]

total_loss = returns['Profit'].sum()
print("Total Loss from Returns:", total_loss)

Total Loss from Returns: -72809.22400000002

In [26]:
returns = df[df['Quantity'] < 0]

total_loss = returns['Profit'].sum()
print("Total Loss from Returns:", total_loss)

Total Loss from Returns: -72809.22400000002

In [27]:
loss_products = df.groupby('Description')['Profit'].sum().sort_values().head(10)
print(loss_products)

Description
Discount                              -1290.308
Manual                                 -779.124
BLUE CHARLIE+LOLA PERSONAL DOORSIGN    -155.760
ADVENT CALENDAR GINGHAM SACK            -92.660
DOORMAT MERRY CHRISTMAS RED             -87.300
CHRISTMAS LIGHTS 10 SANTAS              -55.080
WOODEN BOX ADVENT CALENDAR              -36.180
CHALKBOARD KITCHEN ORGANISER            -35.120
CARDHOLDER GINGHAM CHRISTMAS TREE       -29.580
WHITE CHERRY LIGHTS                     -21.600
Name: Profit, dtype: float64

In [28]:
country_loss = df.groupby('Country')['Profit'].sum().sort_values()
print(country_loss.head(10))

Country
Saudi Arabia             52.468
Canada                   56.216
European Community       76.560
Unspecified             119.640
USA                     153.580
Czech Republic          196.700
Israel                  220.664
United Arab Emirates    355.696
Brazil                  457.440
Lithuania               664.424
Name: Profit, dtype: float64

In [29]:
customer_loss = df.groupby('CustomerID')['Profit'].sum().sort_values()
print(customer_loss.head(10))

CustomerID
14213   -476.880
12503   -450.400
15823   -336.304
17603   -222.360
16252   -118.036
12666    -90.976
17307    -61.056
13958    -40.980
13829    -40.800
16546    -38.372
Name: Profit, dtype: float64

In [30]:
loss_products.to_csv("loss_products.csv")

In [31]:
import pandas as pd
import datetime as dt

today = df['InvoiceDate'].max()

rfm = df.groupby('CustomerID').agg({
    'InvoiceDate': lambda x: (today - x.max()).days,
    'InvoiceNo': 'nunique',
    'Revenue': 'sum',
    'Profit': 'sum'
}).reset_index()

rfm.columns = ['CustomerID', 'Recency', 'Frequency', 'Monetary', 'Profit']

In [32]:
rfm['R_score'] = pd.qcut(rfm['Recency'].rank(method='first'), 4, labels=[4,3,2,1])
rfm['F_score'] = pd.qcut(rfm['Frequency'].rank(method='first'), 4, labels=[1,2,3,4])
rfm['M_score'] = pd.qcut(rfm['Monetary'].rank(method='first'), 4, labels=[1,2,3,4])

In [33]:
def segment(row):
    if row['Profit'] < 0:
        return 'Loss Customers'
    elif row['Monetary'] > 1000 and row['Frequency'] > 5:
        return 'VIP'
    elif row['Frequency'] > 3:
        return 'Loyal'
    elif row['Recency'] > 100:
        return 'At Risk'
    else:
        return 'Regular'

rfm['Segment'] = rfm.apply(segment, axis=1)

In [34]:
loss_customers = rfm[rfm['Profit'] < 0].sort_values('Profit')
loss_customers.head(10)

,CustomerID,Recency,Frequency,Monetary,Profit,R_score,F_score,M_score,Segment
783,14213,151,1,-1192.20,-476.880,1,1,1,Loss Customers
68,12503,117,1,-1126.00,-450.400,1,1,1,Loss Customers
1470,15823,116,2,-840.76,-336.304,1,3,1,Loss Customers
2201,17603,46,1,-555.90,-222.360,2,2,1,Loss Customers
1652,16252,145,1,-295.09,-118.036,1,2,1,Loss Customers
142,12666,138,1,-227.44,-90.976,1,1,1,Loss Customers
2082,17307,144,1,-152.64,-61.056,1,2,1,Loss Customers
673,13958,151,1,-102.45,-40.980,1,1,1,Loss Customers
622,13829,138,1,-102.00,-40.800,1,1,1,Loss Customers
1759,16546,70,3,-95.93,-38.372,2,3,1,Loss Customers

In [35]:
vip_customers = rfm[rfm['Segment'] == 'VIP']
vip_customers.sort_values('Profit', ascending=False).head(10)

,CustomerID,Recency,Frequency,Monetary,Profit,R_score,F_score,M_score,Segment
982,14646,5,18,82259.98,32903.992,4,4,4,VIP
2423,18102,13,10,46318.16,18527.264,4,4,4,VIP
29,12415,5,7,37599.04,15039.616,4,4,4,VIP
2144,17450,6,12,36576.76,14630.704,4,4,4,VIP
758,14156,13,19,35918.80,14367.520,4,4,4,VIP
2162,17511,12,18,28299.69,11319.876,4,4,4,VIP
1148,15061,28,31,26889.76,10755.904,3,4,4,VIP
1090,14911,6,54,24724.69,9889.876,4,4,4,VIP
1446,15769,14,10,24523.92,9809.568,4,4,4,VIP
829,14298,5,25,24003.35,9601.340,4,4,4,VIP

In [36]:
repeat_rate = (rfm['Frequency'] > 1).mean() * 100
print("Repeat Purchase Rate:", repeat_rate)

Repeat Purchase Rate: 54.06813627254509

In [37]:
rfm['CLV'] = rfm['Monetary'] * rfm['Frequency']

In [38]:
df.to_csv("cleaned_retail.csv", index=False)

In [39]:
rfm.to_csv("customer_rfm.csv", index=False)

In [40]:
loss_products.to_csv("loss_products.csv")